### PR TITLE
HPを表示、joystick、など Controller っぽく

### PR DESCRIPTION
**Pull request by shundroid**
This change is [Reviewable](https://reviewable.io/reviews/comozilla/sphero-joystick/21)

### CODE REVIEW

**Comment by zigen** [comment]
Reviewed 22 of 22 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[js/joystick.js, line 5 [r1]](https://reviewable.io:443/reviews/comozilla/sphero-joystick/21#-KLXMIjrMhd0yPYw3TBY:-KLXMIjrMhd0yPYw3TBZ:-1106582606) ([raw file](https://github.com/comozilla/sphero-joystick/blob/4c17024c8e995181f4990ab4e2b1a7c8c965e616/js/joystick.js#L5)):_

> ``` JavaScript
> function Joystick() {
>   this.movementPerPixel = 1;
>   window.addEventListener("resize", () => {
> ```

Joystickクラスがシングルトンでないのだとすると, window.addEventListenerはlistenerを上書きしてしまって, 思わぬバグをうみそう
https://developer.mozilla.org/ja/docs/Web/API/EventTarget/addEventListener

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/sphero-joystick/21)_

**Comment by shundroid** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[js/joystick.js, line 5 [r1]](https://reviewable.io:443/reviews/comozilla/sphero-joystick/21#-KLXMIjrMhd0yPYw3TBY:-KLdCwsVl7d2fv33GKS5:2078850491) ([raw file](https://github.com/comozilla/sphero-joystick/blob/4c17024c8e995181f4990ab4e2b1a7c8c965e616/js/joystick.js#L5)):_
<details><summary>

<i>Previously, hrl7 (Kentaro Teramoto (zigen)) wrote…</i></summary>



> Joystickクラスがシングルトンでないのだとすると, window.addEventListenerはlistenerを上書きしてしまって, 思わぬバグをうみそう
> https://developer.mozilla.org/ja/docs/Web/API/EventTarget/addEventListener
> </details>
> シングルトンでやるのが一番単純でしょうか・・
> とりあえず、このファイルの最後を `export default new Joystick()` としてみます（eventPublisherと同じようなやり方）

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/sphero-joystick/21)_

**Comment by shundroid** [comment]
Review status: 20 of 22 files reviewed at latest revision, 1 unresolved discussion.

---

_[js/joystick.js, line 5 [r1]](https://reviewable.io:443/reviews/comozilla/sphero-joystick/21#-KLXMIjrMhd0yPYw3TBY:-KLdNbk961hztht3KGGg:-2061875081) ([raw file](https://github.com/comozilla/sphero-joystick/blob/4c17024c8e995181f4990ab4e2b1a7c8c965e616/js/joystick.js#L5)):_
<details><summary>

<i>Previously, shundroid wrote…</i></summary>



> シングルトンでやるのが一番単純でしょうか・・
> とりあえず、このファイルの最後を `export default new Joystick()` としてみます（eventPublisherと同じようなやり方）
> </details>
> http://qiita.com/KENJU/items/54760d292d8fbddb1015
> これをみたら、new Joystick(); を何回でもやっても、同じインスタンスを返すような設計にできました。

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/sphero-joystick/21)_

**Comment by zigen** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/sphero-joystick/21)_

**Comment by shundroid** [comment]
Reviewed 7 of 8 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/sphero-joystick/21)_

**Pull request merged**
